{
    "name": "News Assistant - Strategy Digest",
    "version": "18.0.4.1.0",
    "category": "Productivity",
    "summary": "AI-powered strategy digest: label articles by strategic relevance and generate executive briefs",
    "author": "Verein sozialinfo.ch",
    "website": "https://sozialinfo.ch",
    "license": "LGPL-3",
    "depends": [
        "newsassistant_strategy",
        "newsassistant",
        "queue_job",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/strategy_label_views.xml",
        "views/strategy_strategy_views.xml",
        "views/strategy_digest_views.xml",
        "views/news_article_views.xml",
        "views/menu.xml",
        "report/strategy_digest_report.xml",
        "report/strategy_digest_report_template.xml",
    ],
    "demo": [
        "demo/strategy_label_demo.xml",
        "demo/strategy_digest_demo.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}