import logging

from odoo import _, fields, models
from odoo.exceptions import UserError

from odoo.addons.queue_job.exception import RetryableJobError

_logger = logging.getLogger(__name__)


class StrategyStrategy(models.Model):
    _inherit = "strategy.strategy"

    label_ids = fields.Many2many(
        "strategy.label",
        "strategy_strategy_label_rel",
        "strategy_id",
        "label_id",
        string="Labels",
        help="Labels that can be assigned to articles matching this strategy.",
    )
    digest_prompt = fields.Html(
        string="Digest Prompt",
        sanitize=True,
        help="Prompt that defines which articles are relevant and how to label them for the strategy digest. "
             "Generated by the 'Distill' action, but can be edited manually.",
    )

    _DISTILL_DIGEST_SYSTEM_PROMPT = (
        "/no_think\n"
        "You are a strategic analyst. Read the strategy document(s) and extract the main "
        "fields of action or strategic concerns that the strategy addresses. "
        "These will become labels used to tag relevant news articles.\n\n"
        "Instructions:\n"
        "- Identify between 3 and 8 distinct fields of action or strategic themes.\n"
        "- Use short, clear label names (2–5 words max, in the language of the document).\n"
        "- For each label, write a one-sentence description of which news articles "
        "should receive that label.\n"
        "- Then write a single combined evaluation prompt (2–4 sentences) that an AI can use "
        "to decide whether a news article is relevant to this strategy at all, and if so, "
        "which labels to assign.\n\n"
        "Return ONLY a JSON object with exactly this structure — no markdown, no explanation:\n"
        "{\n"
        '  "labels": [\n'
        '    {"name": "Label Name", "description": "Which articles get this label."},\n'
        '    ...\n'
        "  ],\n"
        '  "prompt": "The combined evaluation prompt text."\n'
        "}"
    )

    def action_distill_digest_prompt(self):
        self.ensure_one()
        wizard = self.env["strategy.distill.confirm"].create({
            "strategy_id": self.id,
            "method_name": "_do_distill_digest_prompt",
            "is_plural": False,
        })
        return {
            "type": "ir.actions.act_window",
            "res_model": "strategy.distill.confirm",
            "res_id": wizard.id,
            "view_mode": "form",
            "target": "new",
        }

    def _distill_digest_prompt(self):
        """Run distillation: call AI, create labels, save digest prompt."""
        self.ensure_one()

        content_parts = self._distill_gather_content()
        user_content = f"Strategy name: {self.name}\n\n" + "\n\n".join(content_parts)

        try:
            result = self._call_ai(self._DISTILL_DIGEST_SYSTEM_PROMPT, user_content, temperature=0.3)
        except (RetryableJobError, UserError):
            raise
        except Exception as e:
            raise UserError(_("AI call failed: %s") % str(e)) from e

        try:
            data = self._parse_ai_json(result["content"])
        except Exception as e:
            raise UserError(
                _("AI returned an unexpected response format: %s\n\nRaw response:\n%s")
                % (e, result["content"][:500])
            ) from e

        ai_labels = data.get("labels", [])
        ai_prompt = data.get("prompt", "").strip()

        if not ai_labels:
            raise UserError(
                _("The AI did not identify any labels in the strategy. "
                  "Please check the document content and try again.")
            )
        if not ai_prompt:
            raise UserError(
                _("The AI did not return an evaluation prompt. "
                  "Please check the document content and try again.")
            )

        return self._distill_save_labels_prompt(ai_labels, ai_prompt)

    def _do_distill_digest_prompt(self):
        """Run distillation and return user notification."""
        self.ensure_one()
        self._distill_digest_prompt()

        _logger.info(
            "Strategy '%s': distilled digest prompt with %d label(s).",
            self.name,
            len(self.label_ids),
        )

        label_names_str = ", ".join(lbl.name for lbl in self.label_ids)
        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Digest Prompt Distilled"),
                "message": _(
                    "%(count)d label(s) identified and saved: %(labels)s",
                    count=len(self.label_ids),
                    labels=label_names_str,
                ),
                "type": "success",
                "sticky": True,
            },
        }

    def _distill_save_labels_prompt(self, ai_labels, ai_prompt):
        """Create or reuse strategy.label records and save the prompt."""
        self.ensure_one()
        StrategyLabel = self.env["strategy.label"]
        new_label_ids = []

        for item in ai_labels:
            label_name = (item.get("name") or "").strip()
            if not label_name:
                continue
            existing = StrategyLabel.search([("name", "=ilike", label_name)], limit=1)
            if existing:
                new_label_ids.append(existing.id)
            else:
                new_label = StrategyLabel.create({"name": label_name})
                new_label_ids.append(new_label.id)
                _logger.info("Strategy '%s': created label '%s'", self.name, label_name)

        html_prompt = "<p>" + ai_prompt.replace("\n\n", "</p><p>").replace("\n", "<br>") + "</p>"
        self.write({
            "label_ids": [(6, 0, new_label_ids)],
            "digest_prompt": html_prompt,
        })

        return new_label_ids