import base64
import io
import json
import logging
import os
import time

import requests

from odoo import _, fields, models
from odoo.exceptions import UserError

from odoo.addons.newsassistant.models.utils import html_has_content, html_to_markdown

from odoo.addons.queue_job.exception import RetryableJobError

_logger = logging.getLogger(__name__)

try:
    from pdfminer.high_level import extract_text as pdfminer_extract_text
except ImportError:  # pragma: no cover
    pdfminer_extract_text = None  # pragma: no cover

AI_TIMEOUT = 120
TRANSIENT_HTTP_CODES = {408, 429, 500, 502, 503, 504}
MAX_PDF_TEXT_CHARS = 8000


class StrategyStrategy(models.Model):
    _name = "strategy.strategy"
    _description = "Strategy"
    _order = "name"

    # -------------------------------------------------------------------------
    # Fields
    # -------------------------------------------------------------------------

    name = fields.Char(
        string="Name",
        required=True,
    )
    state = fields.Selection(
        [
            ("draft", "Draft"),
            ("active", "Active"),
            ("archived", "Archived"),
        ],
        string="State",
        default="draft",
        required=True,
        copy=False,
    )
    date_from = fields.Date(
        string="Valid From",
        help="Start date of the strategy (leave empty for no start limit).",
    )
    date_to = fields.Date(
        string="Valid To",
        help="End date of the strategy (leave empty for no end limit).",
    )
    description = fields.Text(
        string="Description",
        help="Text description of the strategy. Used alongside PDF documents for prompt distillation.",
    )
    document_ids = fields.Many2many(
        "ir.attachment",
        "strategy_strategy_attachment_rel",
        "strategy_id",
        "attachment_id",
        string="Strategy Documents",
        domain=[("mimetype", "like", "pdf")],
        help="PDF documents defining this strategy. Used to distill the AI labelling prompt.",
    )
    label_ids = fields.Many2many(
        "strategy.label",
        "strategy_strategy_label_rel",
        "strategy_id",
        "label_id",
        string="Labels",
        help="Labels that can be assigned to articles matching this strategy.",
    )
    prompt = fields.Html(
        string="AI Labelling Prompt",
        help="Prompt that defines which articles are relevant and how to label them. "
             "Generated by the 'Distill Prompt' action, but can be edited manually.",
    )

    # -------------------------------------------------------------------------
    # Actions
    # -------------------------------------------------------------------------

    def action_activate(self):
        """Activate the strategy (auto-distills prompt if not yet set)."""
        self.ensure_one()
        self.write({"state": "active"})

    # -------------------------------------------------------------------------
    # Write override — activation guard / auto-distill
    # -------------------------------------------------------------------------

    def write(self, vals):
        """Auto-distill prompt on activation if not yet set.

        When transitioning to 'active':
        - If a prompt already exists: proceed immediately.
        - If no prompt but content is available (description or documents):
          distill the prompt via AI first, then activate.
        - If no prompt and no content: raise UserError.

        All other state transitions and field writes proceed normally.
        """
        if vals.get("state") == "active":
            for record in self:
                if html_has_content(record.prompt):
                    continue
                has_content = bool(
                    (record.description and record.description.strip())
                    or record.document_ids
                )
                if not has_content:
                    raise UserError(
                        _(
                            "Cannot activate this strategy: no prompt is set and there is "
                            "no content to generate one from.\n\n"
                            "Please add PDF documents or a description first."
                        )
                    )
                record._do_distill_prompt()
        return super().write(vals)

    # -------------------------------------------------------------------------
    # Business Logic Helpers
    # -------------------------------------------------------------------------

    def _is_active_for_period(self, period_from, period_to):
        """Check whether this strategy overlaps with the given period.

        A strategy with no dates is considered eternal (always active).
        A strategy with only date_from is active from that date onwards.
        A strategy with only date_to is active up to that date.
        A strategy with both dates must overlap with the period.

        Args:
            period_from (date): Start of the period (inclusive).
            period_to (date): End of the period (inclusive).

        Returns:
            bool: True if the strategy is active during the period.
        """
        self.ensure_one()
        # No dates at all: eternal
        if not self.date_from and not self.date_to:
            return True
        # Only date_from: active from that date onwards
        if self.date_from and not self.date_to:
            return self.date_from <= period_to
        # Only date_to: active up to that date
        if not self.date_from and self.date_to:
            return self.date_to >= period_from
        # Both dates: must overlap
        return self.date_from <= period_to and self.date_to >= period_from

    def _extract_pdf_text(self, attachment):
        """Extract text from a PDF attachment using pdfminer.

        Args:
            attachment: ir.attachment record with PDF content.

        Returns:
            str: Extracted text (may be empty for scanned PDFs).
        """
        if pdfminer_extract_text is None:  # pragma: no cover
            _logger.warning("pdfminer not available — cannot extract PDF text")  # pragma: no cover
            return ""  # pragma: no cover

        if not attachment.datas:
            return ""

        try:
            pdf_bytes = base64.b64decode(attachment.datas)
            pdf_stream = io.BytesIO(pdf_bytes)
            text = pdfminer_extract_text(pdf_stream)
            return (text or "").strip()
        except Exception as e:
            _logger.warning(
                "Failed to extract text from PDF '%s': %s",
                attachment.name,
                e,
            )
            return ""

    # -------------------------------------------------------------------------
    # AI Infrastructure (self-contained, no cross-module dependency)
    # -------------------------------------------------------------------------

    def _call_ai(self, system_prompt, user_content, temperature=0.1):
        """Call the Infomaniak AI chat completion API.

        Returns:
            dict with keys: content, usage, duration_ms
        """
        api_key = os.environ.get("INFOMANIAK_AI_API_KEY")
        if not api_key:
            raise UserError(
                _("Infomaniak AI API key not configured. "
                  "Set the INFOMANIAK_AI_API_KEY environment variable.")
            )

        product_id = self.env["ir.config_parameter"].sudo().get_param(
            "newsassistant.infomaniak_product_id", default="103794"
        )
        url = f"https://api.infomaniak.com/2/ai/{product_id}/openai/v1/chat/completions"

        model = "qwen3"
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content},
            ],
            "temperature": temperature,
        }
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }

        start_time = time.time()
        try:
            response = requests.post(
                url, json=payload, headers=headers, timeout=AI_TIMEOUT
            )
        except requests.exceptions.Timeout:
            raise RetryableJobError(
                "Infomaniak AI API timeout", seconds=300, ignore_retry=False
            )
        except requests.exceptions.ConnectionError as e:
            raise RetryableJobError(
                f"Infomaniak AI API connection error: {e}",
                seconds=300,
                ignore_retry=False,
            )
        duration_ms = int((time.time() - start_time) * 1000)

        if response.status_code in TRANSIENT_HTTP_CODES:
            raise RetryableJobError(
                f"Infomaniak AI API returned {response.status_code}",
                seconds=300,
                ignore_retry=False,
            )

        if response.status_code != 200:
            raise ValueError(
                f"Infomaniak AI API error {response.status_code}: {response.text[:500]}"
            )

        data = response.json()
        try:
            content = data["choices"][0]["message"]["content"]
        except (KeyError, IndexError) as e:
            raise ValueError(f"Unexpected AI response structure: {e}")

        usage = data.get("usage", {})
        return {
            "content": content,
            "usage": {
                "prompt_tokens": usage.get("prompt_tokens", 0),
                "completion_tokens": usage.get("completion_tokens", 0),
                "total_tokens": usage.get("total_tokens", 0),
            },
            "duration_ms": duration_ms,
        }

    def _parse_ai_json(self, raw_text):
        """Parse JSON from AI response, handling markdown fences and thinking blocks."""
        import re

        text = raw_text.strip()
        text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()

        if text.startswith("```"):
            first_newline = text.find("\n")
            if first_newline != -1:
                text = text[first_newline + 1:]
        if text.endswith("```"):
            text = text[:-3].strip()

        return json.loads(text)

    # -------------------------------------------------------------------------
    # Actions
    # -------------------------------------------------------------------------

    def action_distill_prompt(self):
        """Distill strategy into labels and an AI article-evaluation prompt.

        If a prompt already exists, opens a confirmation wizard first.
        Call _do_distill_prompt() directly to bypass the wizard (used by wizards).

        Steps:
        1. Extract text from all uploaded PDF documents.
        2. Ask the AI to identify the main fields of action / concerns as labels,
           and generate a concise article-evaluation prompt for each label.
        3. Create or reuse strategy.label records for each identified label.
        4. Link the labels to this strategy.
        5. Save the combined evaluation prompt (as HTML) to strategy.prompt.
        """
        self.ensure_one()
        if self.prompt and self.prompt.strip():
            # Prompt already set — open confirmation wizard
            wizard = self.env["strategy.distill.confirm"].create({
                "strategy_id": self.id,
            })
            return {
                "type": "ir.actions.act_window",
                "res_model": "strategy.distill.confirm",
                "res_id": wizard.id,
                "view_mode": "form",
                "target": "new",
            }
        return self._do_distill_prompt()

    def _do_distill_prompt(self):
        """Run the actual distillation logic (bypasses overwrite check).

        Called directly by wizards after user confirmation.
        """
        self.ensure_one()

        # ── 1. Gather source content ──────────────────────────────────────────
        content_parts = []

        for attachment in self.document_ids:
            text = self._extract_pdf_text(attachment)
            if text:
                content_parts.append(
                    f"=== Document: {attachment.name} ===\n{text[:MAX_PDF_TEXT_CHARS]}"
                )
            else:
                _logger.warning(
                    "Strategy '%s': no text extracted from '%s' (possibly scanned PDF)",
                    self.name,
                    attachment.name,
                )

        if self.description and self.description.strip():
            content_parts.append(
                f"=== Strategy Description ===\n{self.description.strip()}"
            )

        if not content_parts:
            raise UserError(
                _("No content available to distill. Please upload PDF documents or add a description.")
            )

        # ── 2. Call AI ────────────────────────────────────────────────────────
        system_prompt = (
            "/no_think\n"
            "You are a strategic analyst. Read the strategy document(s) and extract the main "
            "fields of action or strategic concerns that the strategy addresses. "
            "These will become labels used to tag relevant news articles.\n\n"
            "Instructions:\n"
            "- Identify between 3 and 8 distinct fields of action or strategic themes.\n"
            "- Use short, clear label names (2–5 words max, in the language of the document).\n"
            "- For each label, write a one-sentence description of which news articles "
            "should receive that label.\n"
            "- Then write a single combined evaluation prompt (2–4 sentences) that an AI can use "
            "to decide whether a news article is relevant to this strategy at all, and if so, "
            "which labels to assign.\n\n"
            "Return ONLY a JSON object with exactly this structure — no markdown, no explanation:\n"
            "{\n"
            '  "labels": [\n'
            '    {"name": "Label Name", "description": "Which articles get this label."},\n'
            '    ...\n'
            "  ],\n"
            '  "prompt": "The combined evaluation prompt text."\n'
            "}"
        )

        user_content = (
            f"Strategy name: {self.name}\n\n"
            + "\n\n".join(content_parts)
        )

        try:
            result = self._call_ai(system_prompt, user_content, temperature=0.3)
        except (RetryableJobError, UserError):
            raise
        except Exception as e:
            raise UserError(_("AI call failed: %s") % str(e)) from e

        # ── 3. Parse response ─────────────────────────────────────────────────
        try:
            data = self._parse_ai_json(result["content"])
        except (json.JSONDecodeError, ValueError) as e:
            raise UserError(
                _("AI returned an unexpected response format: %s\n\nRaw response:\n%s")
                % (e, result["content"][:500])
            ) from e

        ai_labels = data.get("labels", [])
        ai_prompt = data.get("prompt", "").strip()

        if not ai_labels:
            raise UserError(
                _("The AI did not identify any labels in the strategy. "
                  "Please check the document content and try again.")
            )
        if not ai_prompt:
            raise UserError(
                _("The AI did not return an evaluation prompt. "
                  "Please check the document content and try again.")
            )

        # ── 4. Create / reuse strategy.label records ──────────────────────────
        StrategyLabel = self.env["strategy.label"]
        new_label_ids = []
        for item in ai_labels:
            label_name = (item.get("name") or "").strip()
            if not label_name:
                continue
            # Reuse an existing label with the same name (case-insensitive), or create
            existing = StrategyLabel.search(
                [("name", "=ilike", label_name)], limit=1
            )
            if existing:
                new_label_ids.append(existing.id)
            else:
                new_label = StrategyLabel.create({"name": label_name})
                new_label_ids.append(new_label.id)
                _logger.info(
                    "Strategy '%s': created label '%s'", self.name, label_name
                )

        # ── 5. Save labels and prompt (as HTML) ───────────────────────────────
        html_prompt = "<p>" + ai_prompt.replace("\n\n", "</p><p>").replace("\n", "<br>") + "</p>"
        self.write({
            "label_ids": [(6, 0, new_label_ids)],
            "prompt": html_prompt,
        })

        _logger.info(
            "Strategy '%s': distilled %d label(s) and evaluation prompt.",
            self.name,
            len(new_label_ids),
        )

        label_names_str = ", ".join(
            lbl.name for lbl in self.label_ids
        )
        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Prompt Distilled"),
                "message": _(
                    "%(count)d label(s) identified and saved: %(labels)s",
                    count=len(new_label_ids),
                    labels=label_names_str,
                ),
                "type": "success",
                "sticky": True,
            },
        }


class StrategyDistillConfirm(models.TransientModel):
    """Wizard: confirm overwrite of an existing prompt before distilling."""

    _name = "strategy.distill.confirm"
    _description = "Confirm Prompt Overwrite"

    strategy_id = fields.Many2one(
        "strategy.strategy",
        string="Strategy",
        required=True,
        ondelete="cascade",
    )

    def action_confirm_distill(self):
        """User confirmed overwrite — run distillation."""
        self.ensure_one()
        return self.strategy_id._do_distill_prompt()
