import logging

from odoo import _, fields, models
from odoo.exceptions import UserError

from odoo.addons.queue_job.exception import RetryableJobError

_logger = logging.getLogger(__name__)


class StrategyStrategy(models.Model):
    _inherit = "strategy.strategy"

    watch_prompt = fields.Html(
        string="Watch Prompt",
        sanitize=True,
        help="Prompt that defines which articles have strategic impact worth watching. "
             "Generated by the 'Distill' action, but can be edited manually.",
    )

    _DISTILL_WATCH_SYSTEM_PROMPT = (
        "/no_think\n"
        "You are a strategic analyst. Read the strategy document(s) and identify "
        "the key criteria that indicate a news article has a significant impact on "
        "the strategy. This will be used to flag articles for a 'strategy watch' "
        "alert — a binary yes/no signal.\n\n"
        "Instructions:\n"
        "- Write a concise evaluation prompt (2–4 sentences) that an AI can use "
        "to decide whether a news article represents a strategic development that "
        "decision-makers should watch closely.\n"
        "- The prompt should help distinguish between routine news and genuinely "
        "significant developments that could affect the strategy.\n"
        "- Focus on impact signals: policy changes, funding announcements, major "
        "organizational changes, new regulations, or emerging trends.\n\n"
        "Return ONLY a JSON object with exactly this structure — no markdown, no explanation:\n"
        "{\n"
        '  "prompt": "The watch evaluation prompt text."\n'
        "}"
    )

    def action_distill_watch_prompt(self):
        self.ensure_one()
        wizard = self.env["strategy.distill.confirm"].create({
            "strategy_id": self.id,
            "method_name": "_do_distill_watch_prompt",
            "is_plural": False,
        })
        return {
            "type": "ir.actions.act_window",
            "res_model": "strategy.distill.confirm",
            "res_id": wizard.id,
            "view_mode": "form",
            "target": "new",
        }

    def _distill_watch_prompt(self):
        """Run distillation: call AI, save watch prompt."""
        self.ensure_one()

        content_parts = self._distill_gather_content()
        user_content = f"Strategy name: {self.name}\n\n" + "\n\n".join(content_parts)

        try:
            result = self._call_ai(self._DISTILL_WATCH_SYSTEM_PROMPT, user_content, temperature=0.3)
        except (RetryableJobError, UserError):
            raise
        except Exception as e:
            raise UserError(_("AI call failed: %s") % str(e)) from e

        try:
            data = self._parse_ai_json(result["content"])
        except Exception as e:
            raise UserError(
                _("AI returned an unexpected response format: %s\n\nRaw response:\n%s")
                % (e, result["content"][:500])
            ) from e

        ai_prompt = data.get("prompt", "").strip()
        if not ai_prompt:
            raise UserError(
                _("The AI did not return a watch prompt. "
                  "Please check the document content and try again.")
            )

        html_prompt = "<p>" + ai_prompt.replace("\n\n", "</p><p>").replace("\n", "<br>") + "</p>"
        self.write({"watch_prompt": html_prompt})

        _logger.info("Strategy '%s': distilled watch prompt.", self.name)

    def _do_distill_watch_prompt(self):
        """Run distillation and return user notification."""
        self.ensure_one()
        self._distill_watch_prompt()

        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Watch Prompt Distilled"),
                "message": _("The watch prompt has been generated and saved."),
                "type": "success",
                "sticky": True,
            },
        }